const homecontroller= require('../app/http/controllers/homeController')
const authcontroller= require('../app/http/controllers/authController')
const cartController = require('../app/http/controllers/customers/cartController')
const guest = require('../app/http/middleware/guest')
const auth = require('../app/http/middleware/auth')
const orderController = require('../app/http/controllers/customers/orderController')
const AdminOrderController = require('../app/http/controllers/admin/orderController')
const admin = require('../app/http/middleware/admin')
const statusController = require('../app/http/controllers/admin/statusController')
function initroutes(app){
    app.get('/', homecontroller().index)
    app.get('/login', guest,authcontroller().login)
    app.post('/login', authcontroller().postLogin)
    app.get('/register', guest, authcontroller().register) 
    app.post('/register',authcontroller().postregister)
    app.post('/logout', auth,authcontroller().logout)
    app.post('/orders',orderController().store)
    app.get('/cart',cartController().index)
    app.post('/update-cart',cartController().update)
    app.get('/customers/orders', auth, orderController().index)
    app.get('/admin/orders', admin, AdminOrderController().index)
    app.post('/admin/order/status',admin, statusController().update)
    app.get('/customers/orders/:id', auth, orderController().show)
}
module.exports = initroutes